services:
  postgres:
    image: postgres:17-alpine
    container_name: payload-postgres

    restart: unless-stopped

    ports:
      - '5432:5432'

    environment:
      POSTGRES_USER: payload
      POSTGRES_PASSWORD: payload
      POSTGRES_DB: payload_dev

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
